### ISSUE TITLE
How to effectively reset conversation.

### ISSUE THREAD

**Issue by MartinBodocky** [digitalbreed/jquery.fbmessenger#7]
I have solution where I have four different use cases. I would like to keep header just change text.

This is inside one content div frame. I have tried to apply reset like following:
element.fbMessenger({
            botName: '...
        })
        .fbMessenger('reset');

or after start:

element
            .fbMessenger('start', { delay: 3000 })
            .fbMessenger('reset')

or before run:
element
.fbMessenger('reset')
            .fbMessenger('run', { timestamp: this.now, delay: 2000 });

All of those ends with error:
Error: Must call start before sending messages
    at Function.error (eval at module.exports (http://localhost:4205/scripts.bundle.js:1:1), <anonymous>:253:9) [angular]
    at b._checkWelcomeMessage (eval at module.exports (http://localhost:4205/scripts.bundle.js:1:1), <anonymous>:11:11579) [angular]
    at b.message (eval at module.exports (http://localhost:4205/scripts.bundle.js:1:1), <anonymous>:11:16119) [angular]
    at eval (eval at module.exports (http://localhost:4205/scripts.bundle.js:1:1), <anonymous>:11:27172) [angular]
    at Object.onInvokeTask (http://localhost:4205/vendor.bundle.js:28650:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4205/vendor.bundle.js:85621:40) [angular]
    at Zone.runTask (http://localhost:4205/vendor.bundle.js:85498:47) [<root> => angular]
    at ZoneTask.invoke (http://localhost:4205/vendor.bundle.js:85692:33) [<root>]
    at data.args.(anonymous function) (http://localhost:4205/vendor.bundle.js:86723:25) [<root>]

What am I doing wrong?

Thanks,

Martin

**Comment by wycoconut** [comment]
Hi Martin,

Just came across this problem as well, I used this approach to workaround it.

```
var runningDemo = $('.phone')
	.fbMessenger({
		botName: 'My Bot',
		botWelcomeMessage: 'This is a simulated Facebook Messenger bot for demonstration purposes only.',
		loop: false,
	});

runningDemo.fbMessenger('init');

runningDemo.fbMessenger('start', { delay: 5 * 1000 });

runningDemo.fbMessenger('message', 'bot', 'Hope this helps', { delay: 1500 });

runningDemo.fbMessenger('run');

```

The line `runningDemo.fbMessenger('init');` does the magic of resetting the conversation.

Hope it helps :)
